apiVersion: v1
kind: Service
metadata:
  name: my-new-service
  labels:
    service: my-new-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31123
    protocol: TCP
  selector:
    app: hello-world
